### ISSUE TITLE
Rounding and other sources of computational approximations

### ISSUE THREAD

**Issue by dumblob** [douglascrockford/DEC64#27]
Could you document how rounding works with DEC64? I've only found this:

```asm
; Rounding is to the nearest value. Ties are rounded away from zero. Integer
; division is floored. The result of modulo has the sign of the divisor.
; There is no negative zero.
```

And how about other sources of approximations (at least all those mentioned in https://github.com/vlang/v/issues/5180#issuecomment-675732199 )? How they're handled in DEC64?

**Comment by douglascrockford** [comment]
That is the rule. What else do you need?

**Comment by dumblob** [comment]
I wanted to see how comparisons are done (whether there is any influence of the "surrounding" like in IEEE 754, how are denormals/subnormals handled, etc.). But I found them right now farther in the asm source. So I think the first question is answered.

Could you maybe comment on other "sources of approximation" other than using the mantissa & exponent way of calculation (i.e. non-constant distribution of numbers on the scale of representable numbers)?

**Comment by douglascrockford** [comment]
Any floating point system will fail to represent exactly some rational numbers. DEC64 can exactly represent all of decimal fractions up to 16 or 17 significant digits. Binary floating point can not. Those are the numbers that are most important to humanity, because that is how humans understand numbers. 

DEC64 does not have subnormals. No sticky bits. No modes. There is a lot of weirdness and complexity in IEEE 754 which is lacking in DEC64.

Comparisons are straightforward. Equality is an exact comparison. 

I still do not understand what you are asking for.

**Comment by dumblob** [comment]
> Any floating point system will fail to represent exactly some rational numbers. DEC64 can exactly represent all of decimal fractions up to 16 or 17 significant digits. Binary floating point can not. Those are the numbers that are most important to humanity, because that is how humans understand numbers.
> 
> DEC64 does not have subnormals. No sticky bits. No modes. There is a lot of weirdness and complexity in IEEE 754 which is lacking in DEC64.
> 
> Comparisons are straightforward. Equality is an exact comparison.
> 
> I still do not understand what you are asking for.

Yep, if this is an **exhaustive** list of (non-)features of DEC64, then it answers my question :wink:. Thanks!
